name: Caller
on:
  push:
jobs:
  test-files:
    name: Test Files
    runs-on: ubuntu-latest
    outputs:
      yaml-changes: ${{ steps.file-changes.outputs.yaml-files }}
      sh-changes: ${{ steps.file-changes.outputs.sh-files }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check for YAML
        uses: dorny/paths-filter@v3
        id: file-changes
        with:
          filters: |
            yaml-files:
              - "**.yml"
              - "**.yaml"
            sh-files:
              - "**.sh"
  call-yaml:
    name: Call YAML WF
    needs: 
      - test-files
    if: needs.test-files.outputs.yaml-changes == 'true'
    uses: james-garriss/test-paths-filter/.github/workflows/yaml-called.yaml@main
  call-sh:
    name: Call Sh WF
    needs: 
      - test-files
    if: needs.test-files.outputs.sh-changes == 'true'
    uses: james-garriss/test-paths-filter/.github/workflows/sh-called.yaml@main
  call-build:
    name: Call Build Wf
    needs:
      - call-yaml
      - call-sh
    if: ${{ !failure() }}
    uses: james-garriss/test-paths-filter/.github/workflows/build-called.yaml@main

