name: Caller
on:
  push:
jobs:
  test-yaml:
    name: Test YAML
    runs-on: ubuntu-latest
    outputs:
      yaml-changes: ${{ steps.yaml-changes.outputs.yaml-files }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check for YAML
        uses: dorny/paths-filter@v3
        id: yaml-changes
        with:
          filters: |
            yaml-files:
              - "**.yml"
              - "**.yaml"
  test-sh:
    name: Test SH
    runs-on: ubuntu-latest
    outputs:
      sh-changes: ${{ steps.sh-changes.outputs.sh-files }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check for Sh
        uses: dorny/paths-filter@v3
        id: sh-changes
        with:
          filters: |
            sh-files:
              - "**.sh"
  call-yaml:
    name: Call YAML WF
    needs: 
      - test-yaml
    if: needs.test-yaml.outputs.yaml-changes == 'true'
    uses: james-garriss/test-paths-filter/.github/workflows/yaml-called.yaml@main
  call-sh:
    name: Call Sh WF
    needs: 
      - test-sh
    if: needs.test-sh.outputs.sh-changes == 'true'
    uses: james-garriss/test-paths-filter/.github/workflows/sh-called.yaml@main
  call-build:
    name: Call Build Wf
    needs:
      - call-yaml
      - call-sh
    if: ${{ always() }}
    uses: james-garriss/test-paths-filter/.github/workflows/build-called.yaml@main

