name: Caller
on:
  push:
jobs:
  test-yaml:
    name: Test YAML
    runs-on: ubuntu-latest
    outputs:
      yaml-changes: ${{ steps.yaml-changes.outputs.yaml-files }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check for YAML
        uses: dorny/paths-filter@v3
        id: yaml-changes
        with:
          filters: |
            yaml-files:
              - "**.yml"
              - "**.yaml"
  call-yaml:
    name: Call YAML Workflow
    needs: 
      - test-yaml
    if: ${{ needs.test-yaml.outputs.yaml-changes }} == 'true'
    uses: james-garriss/test-paths-filter/.github/workflows/called.yaml@main
