name: The workflow that is called
on:
  workflow_call:
jobs:
  yaml-test:
    name: YAML Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List file
        run: ls -al
