name: YAML Called
on:
  workflow_call:
jobs:
  yaml-list:
    name: YAML List
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List file
        run: ls -al
